warning_threshold: 15

excluded:
    - Pods
    - MBUITest
    - UnitTests
    - UITests
    - DerivedData

disabled_rules:
    - trailing_whitespace
    - orphaned_doc_comment

line_length:
    warning: 150

function_parameter_count:
    warning: 10
    error: 15

file_length:
    warning: 500

type_body_length:
    warning: 400
    error: 450
